### ISSUE TITLE
Есть ли в данной программе авторизация приложения по токену?

### ISSUE THREAD

**Issue by mediaexplorer74** [Vladexysys88/HeadHunterDataAnalysing#3]
Здравствуйте.
Есть ли в данной программе авторизация приложения по токену?
Интересно бы увидеть в действии фичи вроде пометка звездочкой интересующих вакансий...

**Comment by Vladexysys88** [comment]
Здравствуйте, пока нету авторизации по токену, возможно сделаю пометку вакансий, но как это может выглядеть в приложении на UI?

**Comment by mediaexplorer74** [comment]
> Здравствуйте, пока нету авторизации по токену возможно сделаю, также возможно сделаю пометку вакансий, но как это может выглядеть в приложении на UI?

Классно. Сам тоже исследую авторизацию по токену. Вожусь с UWP-вариантом приложения. Там устаревший WebView, есть неразрешимые грабли с Auth2 (авторизацией как пользователь по логину-паролю, а не как приложение по clientid).
Мне это для раритетного смарта - винфона Люмка 950 нужно (там штатное приложение HeadHunter давно отвалилось).
Сделал пока лишь примитивный прототип (не для посторонних глаз) для "поднятие резюме" по resumeid. Access Token (именно User Token) вначале вручную через Postman генерю на ноутбуке, потом хардкодю его в UWP-приложение HHResumeRefresh. Черти что, но работает (пока лишь для одного резюме, надо будет усовершенствовать для кучи резюмешек, чтоб вначале получался список айдишек резюме для прогона апдейта циклом).
