### ISSUE TITLE
Есть ли в планах многоплатформенность (моб. приложения на XF или MAUI)?

### ISSUE THREAD

**Issue by mediaexplorer74** [Vladexysys88/HeadHunterDataAnalysing#4]
Есть ли в планах многоплатформенность? Имею ввиду "универсальные" моб. приложения, созданные на XamarinForms или MAUI + .NET6? Ну или накрайняк UWP, чтоб на XBox завелось

**Comment by Vladexysys88** [comment]
Ну может UWP, про телефон маловероятно, пока не знаю

**Comment by mediaexplorer74** [comment]
> Ну может UWP, про телефон маловероятно, пока не знаю

Окей. Спасибо за ответ в любом случае.
Мультиплатформенное мини-приложение сам начал мастерить:
https://github.com/mediaexplorer74/HHExplorer
Чуток продвинулся. Пока лишь список вакансий получаю. Ну и при выборе (точнее смене, эххх) элемента списка вылезает всплывающее окошко, спрашивающее, хотите ли просмореть в веб-браузере детали по вакансии
Никакой авторизации по токену еще не делал, да и поиска по различным фильтрам не наворачивал
